@startuml

state kWaitForHeader
state kWaitForFooter
state kVerifyData
state kValidData : Return payload

[*] --> kWaitForHeader

kWaitForHeader --> kWaitForFooter : header received

kWaitForFooter --> kVerifyData
kWaitForFooter --> kWaitForHeader : invalid footer

kVerifyData --> kValidData
kVerifyData --> kWaitForHeader : checksum error

kValidData --> kWaitForHeader

@enduml
