@startuml

state kHeader0
state kHeader1
state kCommand : clear data\npush to data
state kLength : push to data

state kData : push to data
state kFooter0
state kFooter1

state kValidData : Return payload

[*] --> kHeader0

kHeader0 --> kHeader1 : header byte 0 received

kHeader1 --> kCommand : header byte 1 received
kHeader1 --> kHeader0 : Not header byte 1

kCommand --> kLength

kLength --> kData

kData --> kFooter0
kFooter0 --> kFooter1
kFooter0 --> kHeader0 : Not footer byte 0
kFooter1 --> kVerifyData
kFooter1 --> kHeader0 : Not footer byte 1

kVerifyData --> kValidData
kVerifyData --> kHeader0 : checksum error

kValidData --> kHeader0

@enduml
