# This is the list of all possible parameters
cpp_includes:
  - "wgs84_to_osm_point.hh"
  - "configuration_settings.hh"
  - "time.hh"


parameters:
  current_icon_hash:
    type: uint32_t

  distance_to_next:
    type: uint32_t

  next_street:
    type: std::string

  is_moving:
    type: bool

  # If the phone currently supplies navigation instructions
  navigation_active:
    type: bool

  speed:
    type: uint8_t

  max_speed:
    type: uint8_t

  controller_temperature:
    type: uint8_t

  motor_temperature:
    type: uint8_t

  battery_millivolts:
    type: uint16_t

  # In percent, 0..100
  battery_soc:
    type: uint8_t

  # Milliamphours left in the battery
  battery_milliamphours_left:
    type: uint16_t

  configuration:
    type: struct ConfigurationSettings

  current_power_w:
    type: int16_t

  wh_consumed:
    type: float

  wh_regenerated:
    type: float

  # In meters
  distance_traveled:
    type: uint32_t

  pixel_position:
    type: struct Point

  reset_trip:
    type: Event

  tile_loaded:
    type: Event

  trip_start_time:
    type: milliseconds
